FROM kaspernielsen/javabox

ADD https://repository-dma.forge.cloudbees.com/release/net/maritimecloud/maritimecloud-server/0.1.4/maritimecloud-server-0.1.4.jar /maritimecloud-server.jar

ENTRYPOINT ["java", "-jar", "/maritimecloud-server.jar"]

CMD []

EXPOSE 43234
